// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ykntoouhkvappmttzhpm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlrbnRvb3Voa3ZhcHBtdHR6aHBtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM5NjkxNDAsImV4cCI6MjA1OTU0NTE0MH0.GG0inMteIjI69yrPHC5-sTbhTlSL4dKJb9byJ19UqPo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);